---
version: 2
plugins:
  markdownlint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  reek:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-52
ratings:
  paths:
  - '**.rb'
exclude_patterns:
  - spec/
  - .bettercodehub.yml
  - .codeclimate.yml
  - .fasterer.yml
