#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit(130) }
Signal.trap('SIGINT') { exit(130) }
Signal.trap('TERM') { exit(143) }

require 'bundler/setup'

# require 'luhna'
# require 'luhna/cli'
# require 'luhna/app'
# require 'luhna/reports/accounts_summary'
require 'optparse'

OptionParser.new do |opts|
  opts.banner = 'Usage: bundle exec sodor [OPTION]... [FILE]'

  opts.on('-V', '--version', 'Print version info') do
    $stdout.puts(Sodor::VERSION)
    exit(0)
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    warn(opts)
    exit(0)
  end
end.parse!

# raise 'File not processable' unless Luhna::CLI.processable?

begin
  # app = Luhna::CLI.run(Luhna::App.new, ARGF)

  # Luhna::Reports::AccountsSummary.new(app.bank).run
rescue Errno::EPIPE
  exit(74)
end
