#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit(130) }
Signal.trap('SIGINT') { exit(130) }
Signal.trap('TERM') { exit(143) }

require 'bundler/setup'

require 'sodor'
require 'sodor/cli'
require 'sodor/app'
require 'sodor/lines'
require 'sodor/line'

require 'optparse'

require 'awesome_print'
require 'pry'
require 'byebug'

require 'set'

OptionParser.new do |opts|
  opts.banner = 'Usage: bundle exec sodor [OPTION]... [FILE]'

  opts.on('-V', '--version', 'Print version info') do
    $stdout.puts(Sodor::VERSION)
    exit(0)
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    warn(opts)
    exit(0)
  end
end.parse!

raise 'File not processable' unless Sodor::CLI.processable?

begin
  # app = Sodor::CLI.run(Sodor::App, ARGF)

  # lines = Sodor::Lines.build(ARGF)

  # origins = lines.classify(&:origin)
  # destinations = lines.classify(&:destination)

  puts
rescue Errno::EPIPE
  exit(74)
end
